version: '2'
services:
  namenode:
    image: ramilu90/hadoop-namenode
    container_name: namenode
    platform: linux/amd64
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/friends-mapreduce.txt:/opt/friends-mapreduce.txt
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/resources:/opt/hadoop/resources
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50070:50070

  datanode:
    image: ramilu90/hadoop-datanode
    platform: linux/amd64
    container_name: datanode
    depends_on: 
      - namenode
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50075:50075

  resourcemanager:
    image: ramilu90/hadoop-datanode
    platform: linux/amd64
    hostname: resourcemanager
    container_name: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    depends_on:
      - namenode
      - datanode
    ports:
      - 8088:8088
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: ramilu90/hadoop-datanode
    platform: linux/amd64
    container_name: nodemanager
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./hadoop-hive.env


  spark-master:
    image: ramilu90/spark-master
    container_name: spark-master
    platform: linux/amd64
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-hive.env
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-spark-dockercompose/hadoop_conf:/etc/hadoop/conf 
  spark-worker:
    image: ramilu90/spark-worker
    platform: linux/amd64
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop-hive.env
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-spark-dockercompose/hadoop_conf:/etc/hadoop/conf 
  spark-notebook:
    image: ramilu90/spark-notebook
    platform: linux/amd64
    container_name: spark-notebook
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    env_file:
      - ./hadoop-hive.env
    ports:
      - 9001:9001
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-spark-dockercompose/hadoop_conf:/etc/hadoop/conf 