version: "2"
services:
  namenode:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: namenode
    container_name: namenode
    volumes:
      - ./Makefile:/opt/hadoop/Makefile
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/resources:/opt/hadoop/resources
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/dockercompose/recharge2.input:/opt/recharge2.input
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HDFS_SITE_XML_dfs.webhdfs.enabled: "true"
      CLUSTER_NAME: "test"
    command: ["hdfs", "namenode"]
    deploy:
      resources:
        limits:
          cpus: "1.5"  # limit to 1.5 CPU cores
          memory: "2g"  # limit memory to 2GB
  datanode_1:
    image: apache/hadoop:3
    platform: linux/amd64
    container_name: datanode
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    environment:
      - CLUSTER_NAME=test
  
  resourcemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: resourcemanager
    container_name: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
    environment:
      - CLUSTER_NAME=test
    deploy:
      resources:
        limits:
          cpus: "1.5"  # limit to 1.5 CPU cores
          memory: "2g"  # limit memory to 2GB
  
  nodemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    container_name: nodemanager
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./config
    environment:
      - CLUSTER_NAME=test

  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/recharge.input:/opt/recharge.input
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    platform: linux/amd64
  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    container_name: spark-master
    platform: linux/amd64
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-hive.env
