version: '2'
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    platform: linux/amd64
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/friends-mapreduce.txt:/opt/friends-mapreduce.txt
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/resources:/opt/hadoop/resources
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50070:50070

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    platform: linux/amd64
    depends_on: 
      - namenode
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50075:50075

  resourcemanager:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    platform: linux/amd64
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    depends_on:
      - namenode
      - datanode
    ports:
      - 8088:8088
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    platform: linux/amd64
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./hadoop-hive.env
  pig:
    image: custom-pig
    container_name: pig
    platform: linux/amd64
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    environment:
      - PIG_CONF_DIR=/opt/pig/conf
      - HADOOP_CONF_DIR=/etc/hadoop/conf
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/recharge.input:/opt/recharge.input
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/l_get_friends.pig:/opt/l_get_friends.pig
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/friends.txt:/opt/friends.txt
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/piggybank-0.16.0.jar:/opt/piggybank-0.16.0.jar
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/l_get_friends_mapreduce.pig:/opt/l_get_friends_mapreduce.pig
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/wordcount.pig:/opt/wordcount.pig
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/pig_conf:/opt/pig/conf/
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-pig-dockercompose/hadoop_conf:/etc/hadoop/conf 
    command: tail -f /dev/null

  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    container_name: spark-master
    platform: linux/amd64
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-hive.env

  spark-worker:
    image: bde2020/spark-worker:2.1.0-hadoop2.8-hive-java8
    platform: linux/amd64
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop-hive.env

  spark-notebook:
    image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
    platform: linux/amd64
    container_name: spark-notebook
    env_file:
      - ./hadoop-hive.env
    ports:
      - 9001:9001

  hue:
    image: bde2020/hdfs-filebrowser:3.11
    platform: linux/amd64
    ports:
      - 8089:8088
    environment:
      - NAMENODE_HOST=namenode