version: '3.8'

services:
  namenode:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: namenode
    container_name: namenode
    volumes:
      - ./Makefile:/opt/hadoop/Makefile
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/resources:/opt/hadoop/resources
      # - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/hadoop_dir:/opt/hadoop
    ports:
      - 9870:9870
      - 9000:9000
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HDFS_SITE_XML_dfs.webhdfs.enabled: "true"
      CLUSTER_NAME: "test"
    command: ["hdfs", "namenode"]
    deploy:
      resources:
        limits:
          cpus: "1.5"  # limit to 1.5 CPU cores
          memory: "2g"  # limit memory to 2GB
    networks:
      - hadoop-net

  datanode_1:
    image: apache/hadoop:3
    platform: linux/amd64
    container_name: datanode
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    environment:
      - CLUSTER_NAME=test
    networks:
      - hadoop-net

  resourcemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: resourcemanager
    container_name: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
    environment:
      - CLUSTER_NAME=test
    deploy:
      resources:
        limits:
          cpus: "1.5"  # limit to 1.5 CPU cores
          memory: "2g"  # limit memory to 2GB
    networks:
      - hadoop-net

  nodemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    container_name: nodemanager
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./config
    environment:
      - CLUSTER_NAME=test
    networks:
      - hadoop-net

  hive-metastore:
    image: apache/hive:3.1.3
    platform: linux/amd64
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - HIVE_HOME=/opt/hive
    ports:
      - "9083:9083"  # Thrift Metastore service
    networks:
      - hadoop-net

  hive-server:
    image: apache/hive:3.1.3
    platform: linux/amd64
    container_name: hive-server
    environment:
      - HIVE_SERVER_THRIFT_PORT=10000
      - HIVE_METASTORE_URIS=thrift://hive-metastore:9083
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/hadoop_dir/resources:/opt/hadoop/resources
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/hive-site.xml:/opt/hive/conf/hive-site.xml 
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/wait-for-it.sh:/usr/local/bin/wait-for-it.sh  # Ensure wait-for-it is available
    ports:
      - "10000:10000"  # Thrift interface for Hive queries
    restart: always
    # command: ["--", "hive-server"]
    depends_on:
      - hive-metastore
      - namenode
      - datanode_1
      - resourcemanager
      - nodemanager
    networks:
      - hadoop-net

networks:
  hadoop-net:
    driver: bridge

