version: '2' 
services:
  namenode:
    image: apache/hadoop:3
    container_name: namenode
    platform: linux/amd64
    volumes:
      # - ./data/namenode:/hadoop/dfs/name
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/recharge2.input:/opt/recharge2.input
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50070:50070
  datanode:
    image: apache/hadoop:3
    platform: linux/amd64
    depends_on: 
      - namenode
    # volumes:
    #   - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    ports:
      - 50075:50075

  resourcemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    hostname: resourcemanager
    container_name: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./hadoop-hive.env
    volumes:
      - ./test.sh:/opt/test.sh
    environment:
      - CLUSTER_NAME=test
    deploy:
      resources:
        limits:
          cpus: "1.5"  # limit to 1.5 CPU cores
          memory: "2g"  # limit memory to 2GB
  
  nodemanager:
    image: apache/hadoop:3
    platform: linux/amd64
    container_name: nodemanager
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./hadoop-hive.env
    environment:
      - CLUSTER_NAME=test

  hive-server:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    volumes:
      - /Users/ramindu/iit/lecture4/mapreduce-design-intro/hadoop-hive-dockercompose/recharge.input:/opt/recharge.input
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - "10000:10000"
  hive-metastore:
    image: bde2020/hive:2.1.0-postgresql-metastore
    platform: linux/amd64
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.1.0
    platform: linux/amd64
  spark-master:
    image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
    container_name: spark-master
    platform: linux/amd64
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-hive.env
  spark-worker:
    image: bde2020/spark-worker:2.1.0-hadoop2.8-hive-java8
    platform: linux/amd64
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop-hive.env
  spark-notebook:
    image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
    platform: linux/amd64
    container_name: spark-notebook
    env_file:
      - ./hadoop-hive.env
    ports:
      - 9001:9001
